CREATE TABLE BOARD(
	BID INT PRIMARY KEY,
	TITLE VARCHAR(20) NOT NULL,
	CONTENT VARCHAR(50) NOT NULL,
	WRITER VARCHAR(10),
	CNT INT DEFAULT 0,
	FILENAME VARCHAR(50)
);

INSERT INTO BOARD (BID,TITLE,CONTENT,WRITER) VALUES(1001,'제목','내용','admin');

SELECT * FROM BOARD;

SELECT * FROM BOARD ORDER BY BID DESC;
SELECT * FROM BOARD WHERE TITLE LIKE '%%' ORDER BY BID DESC;