CREATE TABLE BOARD(
	BID INT PRIMARY KEY,
	TITLE VARCHAR(20) NOT NULL,
	CONTENT VARCHAR(50) NOT NULL,
	WRITER VARCHAR(10),
	CNT INT DEFAULT 0
);

INSERT INTO BOARD (BID,TITLE,CONTENT,WRITER) VALUES(1001,'제목','내용','admin');

SELECT * FROM BOARD;